# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('Ph_no', models.IntegerField()),
            ],
        ),
    ]
