# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_App', '0003_auto_20190417_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Username', models.CharField(max_length=200)),
                ('C_Password', models.CharField(max_length=200)),
                ('C_Name', models.CharField(max_length=200)),
                ('C_Address', models.CharField(max_length=200)),
                ('C_Ph_no', models.IntegerField()),
                ('C_Dustbin_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='D_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Username', models.CharField(max_length=200)),
                ('D_Password', models.CharField(max_length=200)),
                ('D_Name', models.CharField(max_length=200)),
                ('D_Address', models.CharField(max_length=200)),
                ('D_Ph_no', models.IntegerField()),
                ('Truck_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('As', models.CharField(choices=[('Client', 'Client'), ('Driver', 'Driver')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='c_details',
            name='C_D_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms_App.D_Details'),
        ),
    ]
