# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_App', '0004_auto_20190423_0624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AlterField(
            model_name='c_details',
            name='C_Ph_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='d_details',
            name='D_Ph_no',
            field=models.CharField(max_length=11),
        ),
    ]
