# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_App', '0006_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trashcan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_ID', models.CharField(max_length=10)),
                ('T_x_c', models.CharField(max_length=14)),
                ('T_y_c', models.CharField(max_length=14)),
                ('T_C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms_App.C_Details')),
                ('T_D_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms_App.D_Details')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='LogIn',
        ),
    ]
