# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_App', '0007_auto_20190429_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='T_C_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Forms_App.C_Details'),
        ),
    ]
