# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_App', '0009_auto_20190429_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcan',
            name='T_D_id',
        ),
    ]
